### ISSUE TITLE
Guardian's Sword crash

### ISSUE THREAD

**Issue by Tslat** [Tslat/Advent-Of-Ascension#1071]
Hit something with charged guardian's sword

`---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 1/17/20 9:03 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.tslat.aoa3.item.weapon.sword.BaseSword.onLeftClickEntity(BaseSword.java:44)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:1067)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1250)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1511)
	at net.minecraft.client.Minecraft.redirect$onClickMouse$zzj000(Minecraft.java:3477)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.tslat.aoa3.item.weapon.sword.BaseSword.onLeftClickEntity(BaseSword.java:44)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:1067)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1250)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1511)
	at net.minecraft.client.Minecraft.redirect$onClickMouse$zzj000(Minecraft.java:3477)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lesweatymonkey07'/572, l='MpServer', x=-246.78, y=64.02, z=259.82]]
	Chunk stats: MultiplayerChunkCache: 1024, 1024
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-172,64,252), Chunk: (at 4,4,12 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11580 game time, 11580 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 74 total; [EntityRamradon['Ramradon'/6146, l='MpServer', x=-288.50, y=54.00, z=286.50], EntityTharafly['Tharafly'/6147, l='MpServer', x=-174.38, y=52.87, z=204.40], EntityRamradon['Ramradon'/6020, l='MpServer', x=-189.50, y=63.00, z=269.50], EntityTharafly['Tharafly'/6151, l='MpServer', x=-189.50, y=26.00, z=331.50], EntityKeeler['Keeler'/6026, l='MpServer', x=-234.50, y=27.00, z=276.50], EntityParasect['Parasect'/6027, l='MpServer', x=-180.76, y=21.00, z=208.60], EntityTharafly['Tharafly'/6032, l='MpServer', x=-151.64, y=26.15, z=282.26], EntityParasect['Parasect'/6160, l='MpServer', x=-209.38, y=50.00, z=192.51], EntityEmperorBeast['Emperor Beast'/6161, l='MpServer', x=-184.50, y=63.00, z=329.50], EntityTharafly['Tharafly'/6034, l='MpServer', x=-178.60, y=114.89, z=301.13], EntityEchodar['Echodar'/6163, l='MpServer', x=-255.50, y=16.00, z=235.50], EntityTharafly['Tharafly'/6036, l='MpServer', x=-304.50, y=46.00, z=285.50], EntityTharafly['Tharafly'/6168, l='MpServer', x=-217.38, y=54.52, z=203.63], EntityKeeler['Keeler'/6169, l='MpServer', x=-278.50, y=24.00, z=268.50], EntityKeeler['Keeler'/6042, l='MpServer', x=-181.34, y=31.00, z=163.52], EntityParasect['Parasect'/6173, l='MpServer', x=-260.12, y=44.00, z=226.62], EntityRamradon['Ramradon'/6046, l='MpServer', x=-302.66, y=30.00, z=268.50], EntityKeeler['Keeler'/6174, l='MpServer', x=-172.51, y=36.00, z=294.44], EntityRamradon['Ramradon'/6048, l='MpServer', x=-266.50, y=19.00, z=299.50], EntityRamradon['Ramradon'/6176, l='MpServer', x=-144.50, y=27.00, z=270.50], EntityTharafly['Tharafly'/6050, l='MpServer', x=-224.61, y=34.84, z=259.96], EntityRamradon['Ramradon'/6052, l='MpServer', x=-244.50, y=20.00, z=297.50], EntityKeeler['Keeler'/6053, l='MpServer', x=-240.50, y=40.00, z=345.50], EntityCryptid['Cryptid'/6182, l='MpServer', x=-253.50, y=21.00, z=157.50], EntityParasect['Parasect'/6183, l='MpServer', x=-314.50, y=36.00, z=287.50], EntityArkback['Arkback'/6056, l='MpServer', x=-261.75, y=63.00, z=222.22], EntityKeeler['Keeler'/6184, l='MpServer', x=-218.50, y=34.00, z=346.50], EntityEchodar['Echodar'/6188, l='MpServer', x=-157.83, y=13.03, z=209.33], EntityArkback['Arkback'/6189, l='MpServer', x=-184.50, y=63.00, z=352.50], EntityParasect['Parasect'/6067, l='MpServer', x=-146.50, y=19.00, z=301.50], EntityTharafly['Tharafly'/6196, l='MpServer', x=-231.95, y=76.63, z=224.15], EntityTharafly['Tharafly'/6198, l='MpServer', x=-235.04, y=74.68, z=299.91], EntityTharafly['Tharafly'/6071, l='MpServer', x=-315.53, y=72.59, z=293.97], EntityEmperorBeast['Emperor Beast'/6199, l='MpServer', x=-229.50, y=63.00, z=344.50], EntityRamradon['Ramradon'/6072, l='MpServer', x=-239.50, y=13.00, z=286.50], EntityArkback['Arkback'/6073, l='MpServer', x=-226.35, y=63.00, z=230.74], EntityEmperorBeast['Emperor Beast'/6202, l='MpServer', x=-199.00, y=67.00, z=171.86], EntityRamradon['Ramradon'/6204, l='MpServer', x=-353.50, y=48.00, z=230.50], EntityEmperorBeast['Emperor Beast'/6079, l='MpServer', x=-271.50, y=63.00, z=337.50], EntityTharafly['Tharafly'/6080, l='MpServer', x=-168.50, y=31.00, z=234.50], EntityArkback['Arkback'/6208, l='MpServer', x=-157.50, y=63.00, z=283.50], EntityKeeler['Keeler'/6211, l='MpServer', x=-291.50, y=28.00, z=281.50], EntityEmperorBeast['Emperor Beast'/6214, l='MpServer', x=-265.50, y=63.00, z=364.50], EntityArkback['Arkback'/6091, l='MpServer', x=-245.80, y=63.00, z=286.13], EntityParasect['Parasect'/6219, l='MpServer', x=-222.50, y=14.00, z=370.50], EntityEmperorBeast['Emperor Beast'/6093, l='MpServer', x=-244.05, y=63.00, z=261.17], EntityRamradon['Ramradon'/6096, l='MpServer', x=-277.50, y=63.00, z=227.50], EntityEmperorBeast['Emperor Beast'/6224, l='MpServer', x=-131.50, y=63.00, z=303.50], EntityRamradon['Ramradon'/6097, l='MpServer', x=-209.34, y=63.00, z=266.57], EntityRamradon['Ramradon'/6230, l='MpServer', x=-147.50, y=26.00, z=241.50], EntityRamradon['Ramradon'/6231, l='MpServer', x=-338.50, y=63.00, z=237.50], EntityRamradon['Ramradon'/6104, l='MpServer', x=-229.73, y=39.00, z=346.66], EntityRamradon['Ramradon'/6235, l='MpServer', x=-304.50, y=41.00, z=289.50], EntityRamradon['Ramradon'/6108, l='MpServer', x=-218.32, y=63.00, z=346.63], EntityTharafly['Tharafly'/6237, l='MpServer', x=-350.51, y=74.27, z=198.38], EntityTharafly['Tharafly'/6111, l='MpServer', x=-224.77, y=66.56, z=223.86], EntityKeeler['Keeler'/6115, l='MpServer', x=-271.50, y=13.00, z=335.50], EntityRamradon['Ramradon'/6247, l='MpServer', x=-212.50, y=63.00, z=283.50], EntityTharafly['Tharafly'/6120, l='MpServer', x=-179.50, y=50.00, z=311.50], EntityTharafly['Tharafly'/6251, l='MpServer', x=-206.50, y=50.00, z=197.50], EntityRamradon['Ramradon'/6252, l='MpServer', x=-359.50, y=42.00, z=216.50], EntityRamradon['Ramradon'/6254, l='MpServer', x=-138.50, y=63.00, z=282.50], EntityPlayerSP['Lesweatymonkey07'/572, l='MpServer', x=-246.78, y=64.02, z=259.82], EntityParasect['Parasect'/6129, l='MpServer', x=-208.50, y=20.00, z=201.50], EntityEmperorBeast['Emperor Beast'/6259, l='MpServer', x=-289.50, y=63.00, z=236.50], EntityParasect['Parasect'/6005, l='MpServer', x=-155.50, y=22.00, z=287.50], EntityEchodar['Echodar'/6007, l='MpServer', x=-223.20, y=24.34, z=309.63], EntityRamradon['Ramradon'/6008, l='MpServer', x=-188.50, y=14.00, z=235.50], EntityArkback['Arkback'/6009, l='MpServer', x=-221.29, y=63.00, z=244.75], EntityCryptid['Cryptid'/6137, l='MpServer', x=-312.50, y=21.00, z=192.50], EntityArkback['Arkback'/6011, l='MpServer', x=-229.50, y=14.00, z=311.50], EntityKeeler['Keeler'/6013, l='MpServer', x=-252.50, y=26.00, z=243.50], EntityKeeler['Keeler'/6142, l='MpServer', x=-287.50, y=25.00, z=216.50], EntityKeeler['Keeler'/6015, l='MpServer', x=-185.50, y=17.00, z=277.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1867634528 bytes (1781 MB) / 6509559808 bytes (6208 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                        | Signature                                |
	|:------ |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | aoa3           | 3.2          | AoA3-3.2.jar                                  | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | codechickenlib | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | jei            | 4.15.0.268   | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LCHIJA | nei            | 2.4.2        | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | torohealthmod  | 1.12.2-11    | torohealth-1.12.2-11.jar                      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz`

**Comment by Tslat** [comment]
Fixed
