### ISSUE TITLE
Exception occurs when extraction skill succeeds

### ISSUE THREAD

**Issue by badfiero** [Tslat/Advent-Of-Ascension#1135]
**Mod Version**
3.2.1 (in server mode)

**Describe the bug**
Exception occurs when extraction skill succeeds.

**To Reproduce**
1. Use the bowl to extraction device.
2. Skill succeeds.
3. Nothing happens and get no items...

**Expected behavior**
Get some items.

**Screenshots**
i have no screen shots sorry. But get exception logs.
[23:41:34] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.tslat.aoa3.utils.StringUtil.getLocaleString(Ljava/lang/String;)Ljava/lang/String;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: net.tslat.aoa3.utils.StringUtil.getLocaleString(Ljava/lang/String;)Ljava/lang/String;
	at net.tslat.aoa3.block.functional.utility.ExtractionDevice.func_180639_a(ExtractionDevice.java:120) ~[ExtractionDevice.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

I think this is the cause, net.tslat.aoa3.utils.StringUtil.getLocaleString is "@SideOnly(Side.CLIENT)".
Can AoA3 not be played in server mode?

Sorry for my poor english.

**Comment by Tslat** [comment]
Fixed
