### ISSUE TITLE
Crash when using Tinkers Construct Shuriken

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#1630]
**Mod Version**
I am using version 3.3.0. This is not the most recent version, but it appears that no Tinker's construct crashes were fixed since this version according to the changelog.

Here is the crashog:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/8/20 10:47 PM
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.tslat.aoa3.hooks.tconstruct.traits.TraitEvilPressure.onHit(TraitEvilPressure.java:28)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:718)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:619)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.dealDamage(EntityProjectileBase.java:322)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.onHitEntity(EntityProjectileBase.java:239)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.updateInAir(EntityProjectileBase.java:445)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:372)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at net.tslat.aoa3.hooks.tconstruct.traits.TraitEvilPressure.onHit(TraitEvilPressure.java:28)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:718)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:619)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.dealDamage(EntityProjectileBase.java:322)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.onHitEntity(EntityProjectileBase.java:239)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.updateInAir(EntityProjectileBase.java:445)
	at slimeknights.tconstruct.library.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:372)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: tconstruct:shuriken (slimeknights.tconstruct.tools.common.entity.EntityShuriken)
	Entity ID: 15416
	Entity Name: entity.shuriken.name
	Entity's Exact location: -723.30, 66.16, -1589.03
	Entity's Block location: World: (-724,66,-1590), Chunk: (at 12,4,10 in -46,-100; contains blocks -736,0,-1600 to -721,255,-1585), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,0,-2048 to -513,255,-1537)
	Entity's Momentum: 0.12, 0.25, 1.87
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 3.3
	All players: 1 total; [EntityPlayerMP['Profilename14'/115, l='3.3', x=-723.51, y=64.00, z=-1592.50]]
	Chunk stats: ServerChunkCache: 554 Drop: 0
	Level seed: -3143587188360663905
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (49,64,-106), Chunk: (at 1,4,6 in 3,-7; contains blocks 48,0,-112 to 63,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 175451 game time, 175451 day time
	Level dimension: 807
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 20253 (now: true), thunder time: 133641 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1905381976 bytes (1817 MB) / 5502926848 bytes (5248 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version           | Source                           | Signature                                |
	|:------ |:---------- |:----------------- |:-------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft  | 1.12.2            | minecraft.jar                    | None                                     |
	| LCHIJA | mcp        | 9.42              | minecraft.jar                    | None                                     |
	| LCHIJA | FML        | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge      | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | aoa3       | 3.3               | AoA3-3.3.jar                     | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | mantle     | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar         | None                                     |
	| LCHIJA | tconstruct | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Profilename14'/115, l='3.3', x=-723.51, y=64.00, z=-1592.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**To Reproduce**
Make a Shyrestone, Magma slime, Rosite, and Varsium shuriken, and then add two levels of sharpness, one level of Fire aspect, and one level of Shulking. Then, throw this shuriken at an enemy several times (took about 3 hits for me) and the game will crash.

**Comment by Tslat** [comment]
Fixed in next version
