### ISSUE TITLE
Crashing while Setup.

### ISSUE THREAD

**Issue by Somebody139** [Tslat/Advent-Of-Ascension#1798]
so i was told before that i have to delete the options.txt to repair this error but when i join my world and set my settings back it crashes again. I am playing v1.12.2 with 31 Mods. i get the same error: java.lang.ArrayIndexOutOfBoundsException: 316

here the full crash:

java.lang.ArrayIndexOutOfBoundsException: 316
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at net.tslat.aoa3.client.event.ClientEventHandler.onPlayerJoin(ClientEventHandler.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_135_ClientEventHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at net.tslat.aoa3.client.event.ClientEventHandler.onPlayerJoin(ClientEventHandler.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_135_ClientEventHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@5de26fa1
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1240288008 bytes (1182 MB) / 4026531840 bytes (3840 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                         | Signature                                |
	|:------ |:------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                  | None                                     |
	| LCHIJA | sampler             | 1.84              | sampler-1.84.jar                               | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | xaerominimap_core   | 1.12.2-1.0        | minecraft.jar                                  | None                                     |
	| LCHIJA | damageindicatorsmod | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.1.jar          | None                                     |
	| LCHIJA | aoa3                | 3.3.4             | AoA3-3.3.4.jar                                 | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | bettercaves         | 1.12.2            | bettercaves-1.12.2-1.6.0.jar                   | None                                     |
	| LCHIJA | blockcraftery       | 1.12.2-1.3.1      | blockcraftery-1.12.2-1.3.1.jar                 | None                                     |
	| LCHIJA | bookshelf           | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ctm                 | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCHIJA | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCHIJA | chisel              | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCHIJA | eplus               | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | forgelin            | 1.8.4             | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | gottschcore         | 1.13.1            | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCHIJA | lootbags            | 2.5.8.5           | LootBags-1.12.2-2.5.8.5.jar                    | None                                     |
	| LCHIJA | lucky               | 7.6.0             | luckyblock-1.12.2-1.jar                        | None                                     |
	| LCHIJA | mm                  | 1.2               | MerchMod-1.2.jar                               | None                                     |
	| LCHIJA | roguelike           | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCHIJA | silentlib           | 3.0.13            | SilentLib-1.12.2-3.0.13+167.jar                | None                                     |
	| LCHIJA | scalinghealth       | 1.3.37            | ScalingHealth-1.12.2-1.3.42+147.jar            | None                                     |
	| LCHIJA | scalingwealth       | 1.0.1             | ScalingWealth-1.0.1.jar                        | None                                     |
	| LCHIJA | treasure2           | 1.12.0            | Treasure2-mc1.12.2-f14.23.5.2768-v1.12.0.jar   | None                                     |
	| LCHIJA | treechopper         | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| LCHIJA | uteamcore           | 2.2.4.107         | u_team_core-1.12.2-2.2.4.107.jar               | None                                     |
	| LCHIJA | usefulbackpacks     | 1.5.1.35          | useful_backpacks-1.12.2-1.5.1.35.jar           | None                                     |
	| LCHIJA | warpbook            | 1.12.2-3.3.4      | Warpbook-1.12.2-3.3.4.jar                      | None                                     |
	| LCHIJA | xaerominimap        | 20.20.0           | Xaeros_Minimap_20.20.0_Forge_1.12.jar          | None                                     |
	| LCHIJA | mysticallib         | 1.12.2-1.7.0      | mysticallib-1.12.2-1.7.0.jar                   | None                                     |

**Comment by EatingSilencer** [comment]
Just curious, what key are you setting the opening the Advent GUI too (called Advent of Ascension Window in the Controls menu)? And does it not crash when you enter the world with chat disabled?

**Comment by Somebody139** [comment]
> Just curious, what key are you setting opening the Advent GUI to (its called Advent of Ascension Window in the Controls menu)? And does it not crash when you enter the world with chat disabled?

Well my key for the menu is </> at german keyboard. Right site of shift. And it still crashes when my chat is disabled

**Comment by EatingSilencer** [comment]
Maybe try setting it to a different key?

**Comment by Somebody139** [comment]
> Maybe try setting it to a different key?

That doesnt do anything...

**Comment by EatingSilencer** [comment]
So it crashes no matter the key you set it too?

**Comment by Somebody139** [comment]
> So it crashes no matter the key you set it too?

Yes

**Comment by Tslat** [comment]
Maybe the game doesn't support the characters you're trying to set it to?

I can't fix you using an invalid keycode. In LWJGL, key 316 does not exist.

Deleting the options.txt to reset your controls back to default should prevent it from crashing, from there you'll need to set it to a key the game recognises..  I can't do anything further with it
