### ISSUE TITLE
Beta 6 Server Crash

### ISSUE THREAD

**Issue by Sl1pstr3am** [Tslat/Advent-Of-Ascension#2107]
**Mod Version**
AoA 1.15.2 Beta 6

**Describe the bug**
The dedicated server crashes during modloading.

**To Reproduce**
Steps to reproduce the behaviour:
Load a dedicated forge server with only the new beta, and attempt to run it.

**Expected behavior**
The server should start as usual.

latest.log:
[04Dec2020 10:49:42.688] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.2.47, --fml.mcpVersion, 20200515.085601, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, nogui]
[04Dec2020 10:49:42.692] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 15.0.1 by Oracle Corporation
[04Dec2020 10:49:42.926] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[04Dec2020 10:49:42.971] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/chris/Desktop/Beta%20Server/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[04Dec2020 10:49:43.188] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/NashornScriptEngineFactory
[04Dec2020 10:49:43.189] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.coremod.CoreModEngine.loadCoreMod(CoreModEngine.java:48)
[04Dec2020 10:49:43.190] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.coremod.CoreModProvider.addCoreMod(CoreModProvider.java:12)
[04Dec2020 10:49:43.191] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[04Dec2020 10:49:43.191] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[04Dec2020 10:49:43.192] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[04Dec2020 10:49:43.192] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[04Dec2020 10:49:43.193] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[04Dec2020 10:49:43.193] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[04Dec2020 10:49:43.194] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[04Dec2020 10:49:43.195] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[04Dec2020 10:49:43.196] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[04Dec2020 10:49:43.197] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[04Dec2020 10:49:43.197] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[04Dec2020 10:49:43.200] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[04Dec2020 10:49:43.201] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[04Dec2020 10:49:43.202] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.fml.loading.LoadingModList.addCoreMods(LoadingModList.java:88)
[04Dec2020 10:49:43.203] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:125)
[04Dec2020 10:49:43.204] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[04Dec2020 10:49:43.205] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[04Dec2020 10:49:43.206] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[04Dec2020 10:49:43.206] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[04Dec2020 10:49:43.207] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
[04Dec2020 10:49:43.209] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1766)
[04Dec2020 10:49:43.210] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[04Dec2020 10:49:43.211] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[04Dec2020 10:49:43.212] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[04Dec2020 10:49:43.213] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[04Dec2020 10:49:43.214] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[04Dec2020 10:49:43.215] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[04Dec2020 10:49:43.215] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[04Dec2020 10:49:43.216] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[04Dec2020 10:49:43.217] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[04Dec2020 10:49:43.219] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[04Dec2020 10:49:43.220] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[04Dec2020 10:49:43.221] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[04Dec2020 10:49:43.222] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.NashornScriptEngineFactory
[04Dec2020 10:49:43.222] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
[04Dec2020 10:49:43.223] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
[04Dec2020 10:49:43.225] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[04Dec2020 10:49:43.225] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	... 35 more

Looks to me like there's a missing class somewhere.

**Comment by Tslat** [comment]
MC runs on Java 8, not 15.
