### ISSUE TITLE
Server kicks players that are joining to the server

### ISSUE THREAD

**Issue by DcZipPL** [Tslat/Advent-Of-Ascension#2753]
**Mod Version**
3.5.4-1.16.5

**Describe the bug**
Server kick players when they join. (Internal Server Error)

**To Reproduce**
Steps to reproduce the behaviour:
1. Make AoA server
2. Try to join to it
3. You got kicked out

**Expected behavior**
Join to server

**Error log**
`[00:43:06] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: UUID string too large
        Index: 15
        Listeners:
                0: HIGH
                1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: NORMAL
                3: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@360247f loggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                4: ASM: class net.blay09.mods.kleeslabs.network.SyncHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                5: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                6: ASM: net.blay09.mods.trashslot.TrashSlot@21de42b3 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: net.minecraftforge.common.ForgeInternalHandler@2d5861b2 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                9: net.minecraftforge.eventbus.EventBus$$Lambda$2845/0x0000000800b76040@44df5fb2
                10: ASM: class me.shedaniel.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                11: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                12: ASM: class corgitaco.enchancedcelestials.EnhancedCelestials$EnhancedCelestialsEvents onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                13: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                14: ASM: class vazkii.quark.base.handler.ContributorRewardHandler onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                15: ASM: class net.tslat.aoa3.event.PlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                16: ASM: snownee.kiwi.contributor.Contributors@760eb57e onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                17: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@55a9933a onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                18: ASM: tschipp.carryon.common.event.ItemEvents@431caca7 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                19: ASM: journeymap.common.events.ForgeEvents@33c0f9ae onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                20: ASM: mekanism.common.CommonPlayerTracker@285a899 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                21: ASM: squeek.appleskin.network.SyncHandler@49accb20 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                22: net.minecraftforge.eventbus.EventBus$$Lambda$2845/0x0000000800b76040@7d8f6a98
                23: ASM: team.creative.creativecore.common.config.event.ConfigEventHandler@54d26dcd playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                24: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@42a9ec25 playerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: UUID string too large
        at java.base/java.util.UUID.fromString(UUID.java:199)
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
        at net.minecraftforge.eventbus.ASMEventHandler_356_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:829)

[00:43:06] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /127.0.0.1:53088
java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString(UUID.java:199) ~[?:?] {}
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323) ~[aoa3:3.5.4-1.16.5] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_356_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}`

**Comment by Tslat** [comment]
Minecraft uses Java 8. Use java 8.
