### ISSUE TITLE
UUID overflow

### ISSUE THREAD

**Issue by Altkase** [Tslat/Advent-Of-Ascension#2778]
**Mod Version**
AoA3-3.5.4-1.16.5

**Describe the bug**
Upon login there is a UUID too long error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Get kicked out.

**Expected behavior**
I am able to log in.

**Screenshots**
![image](https://user-images.githubusercontent.com/87911803/126878135-f3d2c68b-a85b-4026-8bb2-d9b3f6d4f791.png)

```
[18:36:22] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: UUID string too large
        Index: 40
        Listeners:
                0: HIGH
                1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: NORMAL
                3: net.minecraftforge.eventbus.EventBus$$Lambda$2880/0x00007f39b1528908@69daf744
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2880/0x00007f39b1528908@3b713ebd
                5: ASM: class com.feed_the_beast.mods.ftbessentials.FTBEEventHandler playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                6: ASM: com.valkyrieofnight.envirotech.m_voidminer.datapack.voidregistry.VoidMinerDataRegistry@351c79b2 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: se.mickelus.tetra.data.DataManager@7d3018ba playerConnected(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                9: ASM: com.valkyrieofnight.envirotech.m_voidminer.datapack.program.VoidMinerProgramRegistry@7fc95d90 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                10: ASM: class com.alan19.astral.events.astraltravel.StartAndEndHandling sendCapsToPlayer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                11: ASM: class com.alan19.astral.events.astraltravel.PhysicalBodyTracking onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                12: ASM: net.blay09.mods.trashslot.TrashSlot@2cacf64a onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                13: ASM: class me.shedaniel.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                14: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                15: ASM: com.valkyrieofnight.envirocore.m_machines.m_lens_grinder.dp.cat.LensGrinderCategoryRegistry@3777f76a onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                16: ASM: com.valkyrieofnight.envirocore.m_machines.m_lens_grinder.dp.LensGrinderRecipeRegistry@9a9e827 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                17: ASM: class hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache onPlayerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                18: ASM: com.valkyrieofnight.envirocore.m_machines.m_mem_progrm.datapack.cat.MemProgrmCategoryRegistry@8fd85cd onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                19: ASM: class cy.jdkdigital.productivebees.event.EventHandler onPlayerJoinServer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                20: ASM: com.valkyrieofnight.envirocore.m_machines.m_mem_progrm.datapack.MemProgrmRecipeRegistry@28384e89 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                21: ASM: com.valkyrieofnight.envirocore.m_machines.m_assembler.datapack.AssemblerRecipeRegistry@78c5414e onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                22: ASM: com.feed_the_beast.mods.ftbchunks.FTBChunks@472923dd loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                23: ASM: net.minecraftforge.common.ForgeInternalHandler@ce090a1 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                24: ASM: class twilightforest.TFEventListener playerLogsIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                25: ASM: class twilightforest.TFEventListener onClientConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                26: net.minecraftforge.eventbus.EventBus$$Lambda$2880/0x00007f39b1528908@1747b6e0
                27: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                28: ASM: class vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                29: ASM: class vazkii.psi.common.core.handler.LoopcastTrackingHandler onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                30: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                31: ASM: class de.markusbordihn.adaptiveperformancetweaks.player.PlayerOptimization handlePlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                32: ASM: class de.markusbordihn.adaptiveperformancetweaks.player.PlayerManager handlePlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                33: ASM: class sonar.fluxnetworks.register.CommonEventHandler onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                34: ASM: class net.valhelsia.valhelsia_core.event.PlayerJoinWorldListener onPlayerJoinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                35: ASM: de.bluecolored.bluemap.forge.ForgeEventForwarder@23ec271a onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                36: ASM: de.bluecolored.bluemap.forge.ForgeMod@3d0b1f46 onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                37: ASM: org.cyclops.integrateddynamics.core.persist.world.LabelsWorldStorage@4cdccb6e onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                38: ASM: class slimeknights.tconstruct.shared.CommonsEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                39: ASM: class vazkii.quark.base.handler.ContributorRewardHandler onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                40: ASM: class net.tslat.aoa3.event.PlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                41: net.minecraftforge.eventbus.EventBus$$Lambda$2880/0x00007f39b1528908@1d21d71
                42: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@31893a9a onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                43: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@4247d407 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                44: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@5ac2063b onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                45: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@cfbe5fc onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                46: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@1a29da58 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                47: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@43447fdc onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                48: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@1067666c onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                49: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@682c822e onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                50: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@71fd0298 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                51: ASM: com.inventorypets.events.LoginEventHandler@727ee262 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                52: ASM: mekanism.common.CommonPlayerTracker@4bda8527 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                53: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@5cadf45d onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                54: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@5e561efa onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                55: net.minecraftforge.eventbus.EventBus$$Lambda$2880/0x00007f39b1528908@3f0cbad8
                56: net.minecraftforge.eventbus.EventBus$$Lambda$2880/0x00007f39b1528908@d3aef52
                57: ASM: shadows.apotheosis.ench.EnchModuleEvents@41d93cd9 login(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                58: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@6bb459e4 onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: UUID string too large
        at java.base/java.util.UUID.fromString(UUID.java:199)
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
        at net.minecraftforge.eventbus.ASMEventHandler_924_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:829)

[18:36:22] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /217.104.112.36:55868
java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString(UUID.java:199) ~[?:?] {}
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323) ~[aoa3:3.5.4-1.16.5] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_924_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}

```

**Comment by HyDefier** [comment]
Make sure you are using Java version 8 on client and server.

**Comment by Tslat** [comment]
Fixed in next version, but can be locally fixed for now by using java 8

**Comment by dayd21git** [comment]
Where is the fix?
Today I have the same problem and have no way to use JAVA8!
