### ISSUE TITLE
Invaild UUID in code causing 100% error on server login

### ISSUE THREAD

**Issue by sandtechnology** [Tslat/Advent-Of-Ascension#2818]
**Mod Version**
3.5.4

**Describe the bug**
https://github.com/Tslat/Advent-Of-Ascension/blob/dfc01e41f4eda6fcc9748e796d31e3f6b1e38d9b/source/event/PlayerEvents.java#L323-L329
The UUID providing is invalid, causing "UUID string too large" error:
```
java.lang.IllegalArgumentException: UUID string too large
	at java.base/java.util.UUID.fromString1(UUID.java:264)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
	at net.minecraftforge.eventbus.ASMEventHandler_252_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Install the latest version
2. Login to server
3. See the error

**Expected behavior**
Successful to login.

**Screenshots**
None

**Comment by Tslat** [comment]
Known.
We've moved past 3.5 in preparation for the next update

There's a mod that I made quickly to fix it, you'll have to join the Discord server to get it though
