### ISSUE TITLE
exception "UUID string too large" when player login

### ISSUE THREAD

**Issue by MiniDay** [Tslat/Advent-Of-Ascension#2827]
https://github.com/Tslat/Advent-Of-Ascension/blob/dfc01e41f4eda6fcc9748e796d31e3f6b1e38d9b/source/event/PlayerEvents.java#L323

The normal UUID is 36 characters, while the code here has 37 characters. I think it should be wrong.

```
[09:03:02 ERROR]: Exception caught during firing event: UUID string too large
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class net.tslat.aoa3.event.PlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                3: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                4: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                5: ASM: class com.tiviacz.travelersbackpack.handlers.ForgeEventHandler playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                6: ASM: net.minecraftforge.common.ForgeInternalHandler@6acbd4cd playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: mekanism.common.CommonPlayerTracker@6bc39e1e onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@296193dc playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                9: ASM: journeymap.common.events.ForgeEvents@5cfa5816 onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                10: ASM: tschipp.carryon.common.event.ItemEvents@180067f1 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: UUID string too large
        at java.base/java.util.UUID.fromString(Unknown Source)
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
        at net.minecraftforge.eventbus.ASMEventHandler_12_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:56)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:300)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:174)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:76)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by EatingSilencer** [comment]
Known bug. Downgrade to Java 8 for now to fix it.

**Comment by MiniDay** [comment]
> Known bug. Downgrade to Java 8 for now to fix it.

That's too bad. My server (for some reason) can only use Java 11.

It seems that I can only repair this part of the code myself.

**Comment by Tslat** [comment]
Nah I made a patch for this, available on the official discord
