### ISSUE TITLE
Eror loging in on Fresh load

### ISSUE THREAD

**Issue by OneAngryLunatic** [Tslat/Advent-Of-Ascension#2839]
**Mod Version**
AoA3-3.5.4-1.16.5
forge-1.16.5-36.2.4
Magma-1.16.5-36.2.4
Java 15.0.1      ( would prefer to be on 16, but other parts of mods and plugins do not fully support past 15.0.1 yet)

No Other MODS or PLUGINS..... just AOA

**To Reproduce**
1. Delete world
2. load Server (10gb allocation)
3. once server is loaded Load client on separate machine
4. error below is what we get upon login

**Describe the bug**

**Expected behavior**
Expect to login and play game

**Screenshots**
[17:29:52] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player King_Louie__ is e373ab88-7fc0-4794-afcd-847ca5319f85
[17:29:55] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@734c5b86
[17:29:56] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: UUID string too large
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@6e77d089 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: ASM: class net.tslat.aoa3.event.PlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: UUID string too large
        at java.base/java.util.UUID.fromString1(UUID.java:264)
        at java.base/java.util.UUID.fromString(UUID.java:258)
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
        at net.minecraftforge.eventbus.ASMEventHandler_26_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:335)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:171)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:74)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1147)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:379)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1038)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:870)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286)
        at java.base/java.lang.Thread.run(Thread.java:832)

[17:29:56] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.1.111:1115
java.lang.IllegalArgumentException: UUID string too large
        at java.util.UUID.fromString1(UUID.java:264) ~[?:?] {}
        at java.util.UUID.fromString(UUID.java:258) ~[?:?] {}
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323) ~[aoa3:3.5.4-1.16.5] {re:classloading}        at net.minecraftforge.eventbus.ASMEventHandler_26_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:335) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:171) ~[?:?] {re:classloading}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:74) ~[?:?] {re:classloading}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1147) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:379) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1038) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:870) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:832) [?:?] {}
[17:29:57] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: King_Louie__ lost connection: Internal server error
[17:29:57] [Server thread/INFO] [minecraft/DedicatedServer]: King_Louie__ left the game

**Comment by EatingSilencer** [comment]
Known issue.
On the discord server, there is a file that can be installed like a mod that fixes this bug, which you can use in the meantime (access through the pinned messages in general chat). Alternatively, you can switch to Java 8 to fix the issue.
