### ISSUE TITLE
UUID string too large

### ISSUE THREAD

**Issue by dayd21git** [Tslat/Advent-Of-Ascension#2912]
**Mod Version**
AoA3 3.5.4-1.16.5 -> [download](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine/files/3378340)

**Describe the bug**
Upon login there is a UUID too long error.
Today I have the same problem and have no way to use JAVA8!
You haven't solved the problem even after almost 5 months -> [issues](https://github.com/Tslat/Advent-Of-Ascension/issues/2778)

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Get kicked out

**Expected behavior**
I am able to log in

**Screenshots**
It's log!
```
[08:44:56] [User Authenticator #2/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player day-d is 8bd06202-e2b5-3449-8a03-99e2456ff2e1
[08:44:56] [Netty Server IO #4/INFO] [net.minecraftforge.fml.network.FMLHandshakeHandler/]: Client attempting to join with 157 mods : notenoughcrashes, tropicraft, blue_skies, astralsorcery, netherportalfix, hammerlib, betternether, stalwart_dungeons, kleeslabs, the_afterlight, insanelib, neat, bettercaves, ctm, controlling, placebo, citadel, alexsmobs, lordcraft, yungsapi, improvedbackpacks, bookshelf, sophisticatedbackpacks, uteamcore, randompatches, limit-mob-spawn, forcecraft, clickadv, waila, fpsreducer, carryon, jeresources, runesword, twilightforest, supplementaries, konkrete, betterendforge, upgradednetherite, cuneiform, structure_gel, fancyclear, createplus, chocolate, lollipop, astral, heartcanisters, botania, darkerdepths, wilds, schoolsofmagic, dpanvil, curios, eidolon, relics, patchouli, collective, better_diving, redstonemagic, enigmaticlegacy, cavebiomeapi, architectury, extrabotany, aiimprovements, observerlib, itemphysic, cloth-config, undergarden, the_bumblezone, classicbar, scalinghealth, fastleafdecay, codechickenlib, cb_multipart, cb_microblock, cb_multipart_minecraft, nutritionalbalance, geckolib3, betteradvancements, botaniaadditions, ftblibrary, tonsofenchants, someassemblyrequired, aoa3, jei, elementalcraft, druidcraft, feywild, attributefix, abnormals_core, telebeacons, caelus, lemonlib, reap, wawla, invtweaks, fastsuite, clumps, journeymap, roadrunner, naturescompass, configured, libx, assemblylinemachines, vanillatweaks, quantumquarryplus, good_nights_sleep, wolveswitharmor, datafixerslayer, iceandfire, catalogue, randomium, forge, wailaharvestability, castle_dungeons, biomeborderviewer, brandonscore, draconicevolution, spawnbalanceutility, selene, ironchest, minecraft, upgrade_aquatic, earthworks, mousetweaks, mana-and-artifice, silentlib, behgameon, creativecore, chunksavingfix, theurgy, modpacktweaks, krate, pipez, flywheel, create, createautomated, gravestone, ftbbackups, hexblades, fastbench, polymorph, autoreglib, quark, terraincognita, fluxnetworks, fancymenu, fastfurnace, appleskin, ferritecore, enhancedcelestials, cavern, afraidofthedark, cosmeticarmorreworked, valhelsia_core, forbidden_arcanus, deuf, omegacraft
[08:45:12] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@16f9ed5
[08:45:12] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: day-d[/127.0.0.1:59422] logged in with entity id 1 708 at (202,5, 64, 159,5)
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending ToolHandleTypeManager to day-d
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending SnowcapOvenFreezingManager to day-d
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending HorizoniteForgeFuelManager to day-d
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending AlchemyRecipeManager to day-d
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending JournalEntryManager to day-d
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending JournalSectionManager to day-d
[08:45:12] [Server thread/INFO] [ModdingLegacy/blue_skies/]: Sending JournalRequirementManager to day-d
[08:45:13] [Server thread/INFO] [/]:  SpawnBalanceUtility: Zombified piglin and ghasts will be added to Nether Zone.Quest Data sent For: day-d, To: all tracking, Reason: join game
[08:45:13] [Server thread/INFO] [/]: Magic Data sent For: day-d, To: all tracking, Reason: join game
[08:45:13] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: UUID string too large
	Index: 46
	Listeners:
		0: HIGHEST
		1: ASM: io.github.noeppi_noeppi.libx.impl.config.ConfigEvents@62dc8d7a playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: HIGH
		3: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		4: NORMAL
		5: ASM: class net.blay09.mods.kleeslabs.network.SyncHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		6: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		7: ASM: class net.tropicraft.core.common.item.scuba.ScubaData onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: coffee.injected.improvedbackpacks.backpack.BackpackManager$Listener@6d3da8eb onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$2434/0x0000000801555ba0@559569ec
		10: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$2434/0x0000000801555ba0@255c7cef
		12: ASM: com.mrbysco.forcecraft.handlers.PlayerCapHandler@1d9db8d1 onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: com.Rolfmao.upgradednetherite.handlers.ServerConfigHandler@27fafdd8 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: class com.cobbs.lordcraft.Util.Events.ModEvents playerJoinServer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: ASM: class net.mehvahdjukaar.supplementaries.world.data.GlobeData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		17: ASM: class com.alan19.astral.events.astraltravel.StartAndEndHandling sendCapsToPlayer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: ASM: class com.alan19.astral.events.astraltravel.PhysicalBodyTracking onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		19: net.minecraftforge.eventbus.EventBus$$Lambda$2434/0x0000000801555ba0@59d51321
		20: ASM: class mod.beethoven92.betterendforge.common.event.forge.ForgeEvents loginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		21: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.quest_data.QuestDataProvider$Events joinGame(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		22: ASM: class twilightforest.TFEventListener playerLogsIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		23: ASM: class twilightforest.TFEventListener onClientConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		24: ASM: class com.paleimitations.schoolsofmagic.common.data.capabilities.magic_data.MagicDataProvider$Events joinGame(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		25: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		26: ASM: net.spicybanana.wilds.WildsModVariables@39014dcb onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		27: ASM: class net.spicybanana.wilds.procedures.WildsRootGrantProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		28: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticUpdateHandler@6876dacb onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		29: ASM: class me.shedaniel.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		30: ASM: class net.silentchaos512.scalinghealth.event.CommonEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		31: ASM: class hellfirepvp.astralsorcery.common.event.handler.EventHandlerCache onPlayerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		32: ASM: class sirttas.elementalcraft.entity.EntityHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		33: ASM: net.minecraftforge.common.ForgeInternalHandler@30727630 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		34: ASM: quantumquarryplus.QuantumquarryplusModVariables@667be266 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		35: ASM: com.feywild.feywild.EventListener@3ed5b43c playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		36: ASM: class com.brandon3055.brandonscore.handlers.BCEventHandler playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		37: ASM: com.brandon3055.draconicevolution.handlers.DEEventHandler@43202044 login(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		38: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		39: ASM: class com.ma.progression.ProgressionEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		40: ASM: class sonar.fluxnetworks.register.CommonEventHandler onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		41: ASM: class net.valhelsia.valhelsia_core.event.PlayerJoinWorldListener onPlayerJoinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		42: ASM: class com.cobbs.omegacraft.Utils.Events.ForgeEvents playerConnects(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		43: ASM: class com.simibubi.create.events.CommonEvents playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		44: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		45: ASM: class vazkii.quark.base.handler.ContributorRewardHandler onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		46: ASM: class net.tslat.aoa3.event.PlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		47: ASM: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule@14f151c8 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		48: ASM: tschipp.carryon.common.event.ItemEvents@3fbf82de onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		49: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1980a731 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		50: ASM: com.mactso.redstonemagic.events.OnPlayerLoggedIn@3ae624b3 onPlayerLogged(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		51: ASM: journeymap.common.events.ForgeEvents@5fdf0d05 onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		52: ASM: squeek.appleskin.network.SyncHandler@4858f002 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		53: net.minecraftforge.eventbus.EventBus$$Lambda$2434/0x0000000801555ba0@2195af27
		54: net.minecraftforge.eventbus.EventBus$$Lambda$2434/0x0000000801555ba0@5fb168f0
		55: ASM: com.davidm1a2.afraidofthedark.common.event.ResearchTriggerHandler@23554a50 onEvent(Lnet/minecraftforge/eventbus/api/Event;)V
		56: LOW
		57: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@59f51fa6 onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: UUID string too large
	at java.base/java.util.UUID.fromString1(Unknown Source)
	at java.base/java.util.UUID.fromString(Unknown Source)
	at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
	at net.minecraftforge.eventbus.ASMEventHandler_1633_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:56)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:298)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:173)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:75)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
	at java.base/java.lang.Thread.run(Unknown Source)

[08:45:13] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /127.0.0.1:59422
java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString1(Unknown Source) ~[?:?]
	at java.util.UUID.fromString(Unknown Source) ~[?:?]
	at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323) ~[aoa3:3.5.4-1.16.5]
	at net.minecraftforge.eventbus.ASMEventHandler_1633_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:56) ~[forge:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:298) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:173) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:75) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[08:45:13] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: day-d has made the advancement [Ice and Fire]
[08:45:13] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: day-d has made the advancement [Enter the Savanna]
[08:45:17] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: day-d lost connection: Disconnected
[08:45:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: day-d left the game
```

**Comment by Tslat** [comment]
There's a fix, but you have to join the discord community to get it
