### ISSUE TITLE
Rosidian sword still crashed the server

### ISSUE THREAD

**Issue by BambOvC** [Tslat/Advent-Of-Ascension#3053]
**Mod Version**
[AoA3-1.16.5-3.6-Public Alpha]
**Describe the bug**
Rosidian sword still crashed the server.not fixed 

**To Reproduce**
1. Use Rosidian sword
2. Left click to attack any live entity
3. sever crashed

**Comment by EatingSilencer** [comment]
Post new crash report.

**Comment by BambOvC** [comment]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/1/22 5:44 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.World.func_195590_a(Lnet/minecraft/particles/IParticleData;ZDDDDDD)V
	at net.tslat.aoa3.content.item.weapon.sword.RosidianSword.onLeftClickEntity(RosidianSword.java:45) ~[aoa3:1.16.5-3.6-Public Alpha] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:775) ~[forge:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1044) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1292) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1205) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.19.0-18-amd64
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4922402552 bytes (4694 MB) / 6278873088 bytes (5988 MB) up to 8283750400 bytes (7900 MB)
	CPUs: 4
	JVM Flags: 4 total; -Xms1024M -Xmx7900M -XX:+UseG1GC -XX:+UseCompressedOops
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.29.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.29
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.29-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.16-1.3.5.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.3.5               |DONE      |Manifest: NOSIGNATURE
		ImmersiveRailroading-1.16.5-forge-1.9.1.jar       |Immersive Railroading         |immersiverailroading          |1.16.5-forge-1.9.1  |DONE      |Manifest: NOSIGNATURE
		CustomSkinLoader_ForgeLegacy-14.13-SNAPSHOT-314.ja|CustomSkinLoader              |customskinloader              |14.13-SNAPSHOT-314  |DONE      |Manifest: 4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54
		AoA3-1.16.5-3.6-Public+Alpha.jar                  |Advent of Ascension           |aoa3                          |1.16.5-3.6-Public Al|DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.22.jar                      |Carry On                      |carryon                       |1.15.5.22           |DONE      |Manifest: NOSIGNATURE
		TrackAPI-1.16.4-forge-1.2.1.jar                   |TrackAPI                      |trackapi                      |1.2                 |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-11.jar            |Immersive Petroleum           |immersivepetroleum            |3.3.0-11            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.29-universal.jar                |Forge                         |forge                         |36.2.29             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.7-143.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.7-143    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.4.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |22.4.0              |DONE      |Manifest: NOSIGNATURE
		exp_bottling-1.16.3-5.jar                         |EXP Bottling                  |exp_bottling                  |1.16.3-5            |DONE      |Manifest: NOSIGNATURE
		SuperTools-1.2_1.16.5.jar                         |Super Tools                   |supertools                    |1.2                 |DONE      |Manifest: NOSIGNATURE
		UniversalModCore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
		torcherino-14.0.0+1.16.4 .jar                     |Torcherino                    |torcherino                    |14.0.0              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 76fb9597-f92e-4b50-9f54-852b3a6e3384
	Player Count: 1 / 99; [ServerPlayerEntity['wanwushizhu'/508, l='ServerLevel[world]', x=-107.74, y=79.00, z=101.54]]
	Data Packs: vanilla, mod:immersiverailroading (incompatible), mod:aoa3 (incompatible), mod:jei, mod:carryon, mod:trackapi (incompatible), mod:immersivepetroleum, mod:forge, mod:twilightforest, mod:immersiveengineering, mod:neat (incompatible), mod:xaerominimap, mod:supertools, mod:universalmodcore (incompatible), mod:torcherino, mod:customskinloader (incompatible), mod:inventoryprofilesnext (incompatible), mod:exp_bottling
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Cywair** [comment]
I also encountered this issue when I was in my enderman farm killing endermans. So maybe attacking too many mobs in the same time will reproduce the issue.
