### ISSUE TITLE
Crash server, don't know why.

### ISSUE THREAD

**Issue by remanam** [Tslat/Advent-Of-Ascension#311]
aoa3 snapshot10   1.12.2

*
Every time i went across the small river ( i played this mod only 30 minutes) the server chushes.
I didn't do anything and didn't keep in inventory somethine from this mod.
Screenshots i couldn't do.

This is last messages from server

[minecraft/MinecraftServer]: Encountered an unexpected exception 
net.minecraft.util.ReportedException: Ticking entity 
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?] 
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?] 
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?] 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] 
Caused by: java.lang.NullPointerException 
at net.tslat.aoa3.entity.projectiles.mob.BaseMobProjectile.onImpact(BaseMobProjectile.java:34) ~[BaseMobProjectile.class:?] 
at net.minecraft.entity.projectile.EntityThrowable.onUpdate(EntityThrowable.java:249) ~[aev.class:?] 
at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993) ~[amu.class:?] 
at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?] 
at net.minecraft.world.World.updateEntity(World.java:1955) ~[amu.class:?] 
at net.minecraft.world.World.redirect$updateEntity$zzp000(World.java:5117) ~[amu.class:?] 
at net.minecraft.world.World.updateEntities(World.java:1759) ~[amu.class:?] 
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?] 
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?] 
... 4 more 
[39;0m> [K[31;1m[11:47:33] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/srv103396/./crash-reports/crash-2019-02-19_11.47.33-server.txt 
[39;0m> [K[11:47:33] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server 
> [K[11:47:33] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players 
> [K[11:47:33] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds 
> [K[11:47:33] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/overworld 
> [?1h= > [?1h= > [?1h= > [?1h= > [K[11:47:33] [Server thread/INFO] [FML]: Unloading dimension 0 
> [?1h= > [K[11:47:33] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded. 
> [K[11:47:33] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server 
> [K[11:47:33] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players 

I have these mods
IC2,Buildcraft,Forestry, iron chest and still 5 decorate mods, better fps, rustic, architecturecraft, baubles,
Vanilafix,malices door, no more id conflict. 
**Screenshots**
VanilaFix say that Aoa is the problem of crash.

**Comment by Tslat** [comment]
It is an AoA bug but one that is likely fixed after Snapshot 10
