### ISSUE TITLE
Game crashing when removing AoA3 from the mods folder.

### ISSUE THREAD

**Issue by Sebastian6547** [Tslat/Advent-Of-Ascension#3983]
**Mod Version**
1.15.2

**Describe the bug**
I initially created my world with AoA3 in the mod list. I recently wanted to remove it since I wanted to play more vanilla. After loading the world without the mod, it runs fine until I try to load a new chunk. The game crashes 

**To Reproduce**
1. Create a world with AoA3
2. Close the game and remove it from the mods folder.
3. Load back into the world and load new chunk
4. Game crashes.

**Screenshots**
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/78222535/ec190bfb-f1d1-4026-82af-20c08a42ca9f)

**Crash Report**
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/11/23 4:23 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkGenerator.func_222528_a(ChunkGenerator.java:186) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$3(ChunkStatus.java:52) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1614/1780186214.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:664) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$9506/942077731.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:662) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$9503/1082612278.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$9414/531243685.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_222528_a(ChunkGenerator.java:186)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$3(ChunkStatus.java:52)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1614/1780186214.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195)

-- Chunk to be generated --
Details:
	Location: -134,44
	Position hash: 193273528186
	Generator: biomesoplenty.common.world.ChunkGeneratorOverworldBOP@5853204c
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:664)
	at net.minecraft.world.server.ChunkManager$$Lambda$9506/942077731.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:662)
	at net.minecraft.world.server.ChunkManager$$Lambda$9503/1082612278.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$9414/531243685.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['OpGrandma'/326, l='1.15.2 mods 4', x=-1906.07, y=87.66, z=931.53]]
	Chunk stats: ServerChunkCache: 4280
	Level dimension: DimensionType{minecraft:overworld}
	Level name: 1.15.2 mods 4
	Level seed: -4661143129447501022
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-208,98,80), Chunk: (at 0,6,0 in -13,5; contains blocks -208,0,80 to -193,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9139733 game time, 1011393 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 175278 (now: false), thunder time: 57422 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 12314476544 bytes (11744 MB) / 16944988160 bytes (16160 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.15.2_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.47.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.47
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		SaveMyStronghold-1.15.2-1.0.1.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.1 DONE}
		mowziesmobs-1.5.15.jar Mowzie's Mobs {mowziesmobs@1.5.15 DONE}
		SoundControl-1.15.2-1.0.0.2.jar §3Dynamic Surroundings: §eSound Control {sndctrl@1.15.2-1.0.0.1 DONE}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		Overloaded-1.15.2-0.0.86.jar Overloaded {overloaded@1.15.2-0.0.84 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		prefab-1.5.0.3.jar Prefab {prefab@1.5.0.3 DONE}
		futuremc-1.15.2-1.1.0.jar Future MC {futuremc@1.15.2-1.1.0 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		stalwart-dungeons-1.15.2-1.0.0.jar Stalwart Dungeons {stalwart_dungeons@1.0.0 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.1.3.jar TerraForged {terraforged@0.1.3 DONE}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		betteranimalsplus-1.15.2-10.1.0.jar Better Animals Plus {betteranimalsplus@10.1.0 DONE}
		MutantBeasts-1.15.2-1.0.9.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.9 DONE}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 DONE}
		EnhancedVanilla_Snapshot_20w23a-Forge-1.15.2.31.2.0.jar Enhanced Vanilla {enhancedvanilla@Snapshot 20w23a DONE}
		buildinggadgets-3.3.4.jar Building Gadgets {buildinggadgets@3.3.4 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		SimpleOres2-1.15.2-2.1.6.1.jar Simple Ores {simpleores@1.15.2-2.1.6.1 DONE}
		structure-gel-api-1.15.2-1.0.0.jar Structure Gel API {structure_gel@1.0.0 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		forge-1.15.2-31.2.47-client.jar Minecraft {minecraft@1.15.2 DONE}
		FarmersDelight-1.15.2-0.2.4b.jar Farmer's Delight {farmersdelight@1.15.2-0.2.4b DONE}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 DONE}
		Environs-1.15.2-1.0.0.0.jar §3Dynamic Surroundings: §eEnvirons {environs@1.15.2-1.0.0.0 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		pandoras_creatures-1.15.2-1.0.1.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.1 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		BiomesOPlenty-1.15.2-10.0.0.365-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.365 DONE}
		dungeons-plus-1.15.2-1.0.0.jar Dungeons Plus {dungeons_plus@1.0.0 DONE}
		SilentGear-1.15.2-1.11.4+187.jar Silent Gear {silentgear@1.11.4+187 DONE}
		BetterDefaultBiomes-1.15.2-Alpha+1.3.5.jar Better Default Biomes {betterdefaultbiomes@Alpha 1.3.5 DONE}
		MobEffects-1.15.2-1.0.0.0.jar §3Dynamic Surroundings: §eMob Effects {mobeffects@1.15.2-1.0.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.7.jar Curios API {curios@FORGE-1.15.2-2.0.2.7 DONE}
		Artifacts-1.15.2-2.5.3.jar Artifacts {artifacts@1.15.2-2.5.3 DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		Xaeros_Minimap_20.5.2_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.2 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		hunterillager-1.15.2-0.7.2.jar HunterIllager {hunterillager@0.7.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		byg-1.0.11.jar Oh The Biomes You'll Go {byg@1.0.11 DONE}
		SilentGems-1.15.2-3.6.2+98.jar Silent's Gems 3 {silentgems@3.6.2+98 DONE}
		illagers_plus-2.2.jar Illagers+ {illagers_plus@2.2 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		LegendOfHerobrine-1.15.2-0.4.6-b2.jar The Legend of Herobrine {herobrine@0.4.6-b2 DONE}
		SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 DONE}
		BetterMineshaftsForge-1.15.2-1.3.2.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.2 DONE}
		NetherEx-1.15.2-4.0.1.jar NetherEx {netherex@4.0.1 DONE}
		LibraryEx-1.15.2-3.0.2.jar LibraryEx {libraryex@3.0.2 DONE}
		Cyclic-1.15.2-0.1.7.jar Cyclic {cyclic@1.15.2-0.1.7 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['OpGrandma'/326, l='1.15.2 mods 4', x=-1906.07, y=87.66, z=931.53]]
	Data Packs: mod:waila (incompatible), mod:futuremc (incompatible), mod:stalwart_dungeons, mod:hunterillager, mod:illagers_plus, netherex:netherex_nether_biome_pack (incompatible), netherex:enb_nether_biome_pack (incompatible), netherex:default_nether_biome_pack (incompatible), netherex:byg_nether_biome_pack (incompatible), netherex:bop_nether_biome_pack (incompatible), vanilla, mod:savemystronghold (incompatible), mod:mowziesmobs (incompatible), mod:sndctrl (incompatible), mod:torchslabmod, mod:damage_indicator (incompatible), mod:overloaded (incompatible), mod:jei (incompatible), mod:prefab, mod:attributefix (incompatible), mod:abnormals_core, mod:kleeslabs (incompatible), mod:bettercaves (incompatible), mod:terraforged, mod:xaeroworldmap, mod:placebo (incompatible), mod:decorative_blocks, mod:dungeoncrawl (incompatible), mod:betteranimalsplus (incompatible), mod:mutantbeasts, mod:guardvillagers (incompatible), mod:enhancedvanilla, mod:buildinggadgets (incompatible), mod:forge (incompatible), mod:refinedstorage (incompatible), mod:simpleores, mod:structure_gel, mod:ironchest, mod:farmersdelight, mod:repurposed_structures, mod:environs (incompatible), mod:swingthroughgrass (incompatible), mod:pandoras_creatures, mod:ambientsounds (incompatible), mod:silentlib (incompatible), mod:biomesoplenty, mod:dungeons_plus, mod:silentgear (incompatible), mod:betterdefaultbiomes, mod:mobeffects (incompatible), mod:curios (incompatible), mod:artifacts, mod:savageandravage, mod:xaerominimap, mod:oreexcavation (incompatible), mod:cfm (incompatible), mod:byg, mod:silentgems (incompatible), mod:charm (incompatible), mod:herobrine, mod:soundfilters (incompatible), mod:bettermineshafts (incompatible), mod:netherex (incompatible), mod:libraryex (incompatible), mod:cyclic (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.50+Extreme-VL
	OpenGlVersion: 4.6.0 NVIDIA 537.58
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Tslat** [comment]
1.15.2 is a long dead version
