### ISSUE TITLE
Crashing issue since today (3.0.1, fixed in 3.0.2)

### ISSUE THREAD

**Issue by xhatz** [Tslat/Advent-Of-Ascension#400]
**Mod Version**
3.0.1 (right after 3.0.2 was released)

**Describe the bug**
Game crashes at launch for one of my players:

```
[B#402] 2019/02/26 14:16:10 [INFOS]  Time: 2/26/19 2:16 PM
[B#402] 2019/02/26 14:16:10 [INFOS]  Description: There was a severe problem during mod loading that has caused the game to fail
[B#402] 2019/02/26 14:16:10 [INFOS]  
[B#402] 2019/02/26 14:16:10 [INFOS]  net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AdventOfAscension (aoa3)
[B#402] 2019/02/26 14:16:10 [INFOS]  Caused by: java.lang.NullPointerException
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.tslat.aoa3.client.gui.render.LoginNoticeRenderer.doNoRenderUpdateMessage(LoginNoticeRenderer.java:73)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.tslat.aoa3.common.ClientProxy.registerClientEvents(ClientProxy.java:78)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.tslat.aoa3.common.ClientProxy.preInit(ClientProxy.java:26)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.tslat.aoa3.advent.AdventOfAscension.fmlPreInit(AdventOfAscension.java:60)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraft.client.main.Main.main(SourceFile:123)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#402] 2019/02/26 14:16:10 [INFOS]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Thank you!

**Comment by masterbobli** [comment]
Why bother submitting the report of a fixed bug?

**Comment by xhatz** [comment]
Because it could be problematic in the future for servers that are taking longer to update, it would prevent players from playing entirely for a period of time.
