### ISSUE TITLE
netty error

### ISSUE THREAD

**Issue by Esstoo** [Tslat/Advent-Of-Ascension#4105]
**Mod Version**
1.20.4 Neoforge

**Describe the bug**
When trying to connect to a server that has the mod, it gives me this error:

> Internal Exception: io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException

I've tried opening the game to lan and getting my friend on, but he gets the exact same error
Mod works just fine in solo
I just recently swithced to Neoforge, so I tried other mods to see if neoforge was the problem, and they run just fine.
Error only occurs with AoA

```
[25févr.2024 19:26:30.770] [Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to ---
[25févr.2024 19:26:30.833] [Server Connector #4/DEBUG] [net.neoforged.neoforge.network.DualStackUtils/]: Detected IPv4 address: ---
[25févr.2024 19:26:32.496] [Netty Client IO #9/DEBUG] [net.neoforged.neoforge.common.NeoForgeConfig/FORGEMOD]: NeoForge config just got changed on the file system!
[25févr.2024 19:26:33.745] [Netty Client IO #9/ERROR] [net.minecraft.network.Connection/]: Exception caught in connection
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar%23149!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar%23153!/:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23148!/:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23148!/:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:167) ~[?:?]
	at net.minecraft.core.NonNullList.remove(NonNullList.java:83) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.tslat.aoa3.content.recipe.ImbuingRecipe$Factory.fromNetwork(ImbuingRecipe.java:278) ~[AoA3-1.20.4-3.7.4.jar%23177!/:?]
	at net.tslat.aoa3.content.recipe.ImbuingRecipe$Factory.fromNetwork(ImbuingRecipe.java:261) ~[AoA3-1.20.4-3.7.4.jar%23177!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.fromNetwork(ClientboundUpdateRecipesPacket.java:46) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.FriendlyByteBuf.readCollection(FriendlyByteBuf.java:188) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.FriendlyByteBuf.readList(FriendlyByteBuf.java:203) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:23) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.ConnectionProtocol$PacketSet.lambda$addPacket$1(ConnectionProtocol.java:598) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.ConnectionProtocol$PacketSet.createPacket(ConnectionProtocol.java:665) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.ConnectionProtocol$CodecData.createPacket(ConnectionProtocol.java:562) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:31) ~[client-1.20.4-20231207.154220-srg.jar%23178!/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar%23147!/:4.1.97.Final]
	... 36 more
[25févr.2024 19:26:34.604] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Welcome to Advent of Ascension! Press Delete to view your stats
[25févr.2024 19:26:34.663] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException
[25févr.2024 19:27:49.230] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

```

**Screenshots**
![Screenshot 2024-02-24 194340](https://github.com/Tslat/Advent-Of-Ascension/assets/88528068/9556b5ea-2d8f-41a5-815e-e904a96b50d7)

**Comment by 3269199948** [comment]
I am encountering the same problem, please update the mod version in curseforge!
