### ISSUE TITLE
Cannot run on server newforge

### ISSUE THREAD

**Issue by zezhwe123** [Tslat/Advent-Of-Ascension#4190]
**Mod Version**
1.21

**Describe the bug**
If it cannot be applied to the server, an error will be reported.

The server is newforge-21.0.37-beta
[latest.log](https://github.com/user-attachments/files/15969024/latest.log)

The following is the server error 

[256月2024 17:52:57.299] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 21.0.37-beta, --fml.fmlVersion, 4.0.6, --fml.mcVersion, 1.21, --fml.neoFormVersion, 20240613.152323]
[256月2024 17:52:57.306] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Azul Systems, Inc. OpenJDK 64-Bit Server VM 21.0.3+9-LTS
[256月2024 17:52:57.309] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 11.0.3+main.0f24dec3 starting: java version 21.0.3 by Azul Systems, Inc.; OS Windows Server 2022 arch amd64 version 10.0
[256月2024 17:52:57.538] [main/INFO] [net.neoforged.fml.loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[256月2024 17:52:57.637] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Administrator/Desktop/1.21newforge/libraries/net/fabricmc/sponge-mixin/0.13.4+mixin.0.8.5/sponge-mixin-0.13.4+mixin.0.8.5.jar%2375!/ Service=ModLauncher Env=SERVER
[256月2024 17:52:57.968] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "server-1.21-20240613.152323-srg.jar" [locator: production server provider +net.neoforged:neoforge:21.0.37-beta:server]
[256月2024 17:52:57.986] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-21.0.37-beta-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[libraries\net\neoforged\neoforge\21.0.37-beta\neoforge-21.0.37-beta-universal.jar]], reader: mod manifest]
[256月2024 17:52:58.022] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "AoA3-1.21-3.7.8.jar" [locator: {mods folder locator at C:\Users\Administrator\Desktop\1.21newforge\mods}, reader: mod manifest]
[256月2024 17:52:58.433] [main/INFO] [net.neoforged.fml.loading.moddiscovery.locators.JarInJarDependencyLocator/]: Found 5 dependencies adding them to mods collection
[256月2024 17:52:58.435] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "SmartBrainLib-neoforge-1.21-1.14.3.jar" [parent: AoA3-1.21-3.7.8.jar, locator: jarinjar, reader: mod manifest]
[256月2024 17:52:58.435] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "geckolib-neoforge-1.21-4.5.6.jar" [parent: AoA3-1.21-3.7.8.jar, locator: jarinjar, reader: mod manifest]
[256月2024 17:52:58.436] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "TslatEffectsLib-neoforge-1.21-1.9.jar" [parent: AoA3-1.21-3.7.8.jar, locator: jarinjar, reader: mod manifest]
[256月2024 17:52:58.436] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found library file "hsqldb-2.7.3.jar" [parent: AoA3-1.21-3.7.8.jar, locator: jarinjar]
[256月2024 17:52:58.437] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found gamelibrary file "mixinextras-neoforge-0.3.5.jar" [parent: neoforge-21.0.37-beta-universal.jar, locator: jarinjar, reader: mod manifest]
[256月2024 17:52:58.867] [main/INFO] [net.neoforged.fml.loading.FMLServiceProvider/CORE]: Loading coremod script-engine for [neoforge]
[256月2024 17:53:00.872] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[256月2024 17:53:00.877] [main/INFO] [mixin/]: Compatibility level set to JAVA_21
[256月2024 17:53:00.899] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[256月2024 17:53:00.988] [main/WARN] [mixin/]: Reference map 'geckolib.refmap.json' for geckolib.mixins.json could not be read. If this is a development environment you can ignore this message
[256月2024 17:53:00.999] [main/WARN] [mixin/]: Reference map 'tslateffectslib.refmap.json' for tslateffectslib.mixins.json could not be read. If this is a development environment you can ignore this message
[256月2024 17:53:03.756] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[256月2024 17:53:13.680] [modloading-worker-0/INFO] [net.neoforged.neoforge.common.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 21.0.37-beta, for MC 1.21
[256月2024 17:53:15.016] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: aoa3, class net.tslat.aoa3.advent.AdventOfAscension
java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/living/LivingAttackEvent
	at TRANSFORMER/aoa3@3.7.8/net.tslat.aoa3.event.PlayerEvents.preInit(PlayerEvents.java:70) ~[AoA3-1.21-3.7.8.jar%23123!/:3.7.8]
	at TRANSFORMER/aoa3@3.7.8/net.tslat.aoa3.advent.AdventOfAscension.initEventHandlers(AdventOfAscension.java:72) ~[AoA3-1.21-3.7.8.jar%23123!/:3.7.8]
	at TRANSFORMER/aoa3@3.7.8/net.tslat.aoa3.advent.AdventOfAscension.<init>(AdventOfAscension.java:46) ~[AoA3-1.21-3.7.8.jar%23123!/:3.7.8]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:152) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:230) ~[loader-4.0.6.jar%2360!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
Caused by: java.lang.ClassNotFoundException: net.neoforged.neoforge.event.entity.living.LivingAttackEvent
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 17 more
[256月2024 17:53:15.031] [main/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to wait for future Mod Construction, 1 errors found
[256月2024 17:53:15.195] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID bce71814-951d-463f-95ce-3430fd0b4b04
[256月2024 17:53:15.198] [main/FATAL] [net.neoforged.neoforge.server.loading.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2024-06-25_17.53.15-fml.txt
[256月2024 17:53:15.202] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID c4edb668-ed35-4fae-b026-06a310a66779
[256月2024 17:53:15.204] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Advent Of Ascension (aoa3) has failed to load correctly
	  java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/living/LivingAttackEvent

	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:280) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:243) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:151) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:141) ~[loader-4.0.6.jar%2360!/:4.0]
	at TRANSFORMER/neoforge@21.0.37-beta/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:47) ~[neoforge-21.0.37-beta-universal.jar%23122!/:?]
	at TRANSFORMER/neoforge@21.0.37-beta/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[neoforge-21.0.37-beta-universal.jar%23122!/:?]
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23121!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.6.jar%2360!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.3.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.3.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.3.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.3.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.3.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.3.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.3.jar%2362!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]

**Comment by Tslat** [comment]
Yeah neoforge made breaking changes
Use .30 until I update next

**Comment by zezhwe123** [comment]
> 是的，neoforge 进行了重大更改，请使用 .30，直到我下次更新

Thank you for your help. I will always support Advent-Of-Ascension.
