### ISSUE TITLE
Crash after Goldorth is hit by Industrial Foregoing mob crusher

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#509]
Probably because he's trying to teleport the fake player to him.

Won't happen in survival, I know, but I'm sure it can be fixed

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  BetterSprintingCore (BetterSprinting-1.12.2-v2.1.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 3/23/19 12:26 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.player.EntityPlayerMP.func_70634_a(EntityPlayerMP.java:1220)
	at net.tslat.aoa3.entity.boss.goldorth.EntityGoldorth.func_70636_d(EntityGoldorth.java:93)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_70634_a(EntityPlayerMP.java:1220)
	at net.tslat.aoa3.entity.boss.goldorth.EntityGoldorth.func_70636_d(EntityGoldorth.java:93)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: aoa3:goldorth (net.tslat.aoa3.entity.boss.goldorth.EntityGoldorth)
	Entity ID: 211524
	Entity Name: Goldorth
	Entity's Exact location: 257.00, 72.00, 178.00
	Entity's Block location: World: (257,72,178), Chunk: (at 1,4,2 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['removed'/211680, l='New World', x=257.86, y=71.00, z=180.32]]
	Chunk stats: ServerChunkCache: 310 Drop: 0
	Level seed: 3085664500473551228
	Level generator: ID 31 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (256,64,180), Chunk: (at 0,4,4 in 16,11; contains blocks 256,0,176 to 271,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 238923 game time, 247098 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19825 (now: false), thunder time: 147206 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1216784960 bytes (1160 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State                    | ID                                | Version           | Source                                          | Signature                                |
	|:------------------------ |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAAAAAAA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | forge                             | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | foamfixcore                       | 7.7.4             | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | aether_legacy                     | 1.12.2-v1.4.3     | aether_legacy-1.12.2-v1.4.3.jar                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | aoa3                              | 3.0.2             | AoA3-3.0.2.jar                                  | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | ctm                               | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | appliedenergistics2               | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | jei                               | 4.14.4.264        | jei_1.12.2-4.14.4.264.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | quark                             | r1.5-146          | Quark-r1.5-146.jar                              | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | autoreglib                        | 1.3-26            | AutoRegLib-1.3-26.jar                           | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | bettersprinting                   | 2.1.2             | BetterSprinting-1.12.2-v2.1.2.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | bibliocraft                       | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | biomesoplenty                     | 7.0.1.2419        | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | botania                           | r1.10-359         | Botania+r1.10-359.jar                           | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | chickenchunks                     | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | chisel                            | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAAAAAAAAAAAA | cofhcore                          | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | cofhworld                         | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAAAAAAAAAAAA | endercore                         | 1.12.2-0.5.45     | EnderCore-1.12.2-0.5.45.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | thermalfoundation                 | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAAAAAAAAAAAA | thermalexpansion                  | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderio                           | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderiointegrationtic             | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderiobase                       | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderioconduits                   | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderioconduitsappliedenergistics | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderioconduitsopencomputers      | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderioconduitsrefinedstorage     | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mantle                            | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | natura                            | 1.12.2-4.3.2.66   | natura-1.12.2-4.3.2.66.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | forestry                          | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderiointegrationforestry        | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | twilightforest                    | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | tconstruct                        | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderiointegrationticlate         | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderiomachines                   | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | enderiopowertools                 | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | erebus                            | 1.0.28            | Erebus-1.0.28.jar                               | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | foamfix                           | 0.10.3-1.12.2     | foamfix-0.10.3-1.12.2.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | forgelin                          | 1.8.2             | Forgelin-1.8.2.jar                              | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | ichunutil                         | 7.2.0             | iChunUtil-1.12.2-7.2.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | gravitygun                        | 7.0.0             | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | teslacorelib                      | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.5-229.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | journeymap                        | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | jeid                              | 1.0.2-26          | JustEnoughIDs-1.0.2-26.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mystcraft                         | 0.13.6.00         | mystcraft-1.12.2-0.13.6.00.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | gbook                             | 2.8.3             | Guidebook-1.12.2-2.8.3.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | ltta                              | 1.3.1             | ltta-1.12.2-1.3.1.jar                           | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mkmmod                            | 1.0               | MobKillMessages-1.12.2-1.0.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | moremystcraft                     | 0.5.3             | moremystcraft-1.12.2-0.5.3.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | mystcraft_info                    | 1.0.3.0           | mystcraft_info-1.12.2-1.0.3.0.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | recipehandler                     | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | portalgun                         | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | thermaldynamics                   | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAAAAAAAAAAAA | torohealthmod                     | 1.12.2-11         | torohealth-1.12.2-11.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAA | immersiveengineering              | 0.12-89           | ImmersiveEngineering-0.12-89.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | thebetweenlands                   | 3.4.6             | TheBetweenlands-3.4.6-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAAAAAAAAAAAAAAAAA | teslacorelib_registries           | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
BetterSprintingCore (BetterSprinting-1.12.2-v2.1.2.jar)
  chylex.bettersprinting.system.core.TransformerEntityPlayerSP
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['removed'/211680, l='New World', x=257.86, y=71.00, z=180.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 399.07
	OpenGlRenderer: GeForce 940M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Tslat** [comment]
Believe it or not, this is actually industrial foregoing's problem, not AoA's.
