### ISSUE TITLE
Soulscorne crash

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#516]
Was walking around and got near some soulscornes then it crashed.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  BetterSprintingCore (BetterSprinting-1.12.2-v2.1.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/24/19 11:49 PM
Description: Ticking entity

java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1441)
	at net.tslat.aoa3.entity.mobs.shyrelands.EntitySoulscorne.doMeleeEffect(EntitySoulscorne.java:98)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_70652_k(AoAMeleeMob.java:187)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.remove(HashMap.java:1441)
	at net.tslat.aoa3.entity.mobs.shyrelands.EntitySoulscorne.doMeleeEffect(EntitySoulscorne.java:98)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_70652_k(AoAMeleeMob.java:187)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: aoa3:soulscorne (net.tslat.aoa3.entity.mobs.shyrelands.EntitySoulscorne)
	Entity ID: 78102
	Entity Name: Soulscorne
	Entity's Exact location: 438.58, 31.00, 173.22
	Entity's Block location: World: (438,31,173), Chunk: (at 6,1,13 in 27,10; contains blocks 432,0,160 to 447,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.08, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: AoA3 Survival World
	All players: 1 total; [EntityPlayerMP['removed'/932, l='AoA3 Survival World', x=439.31, y=31.00, z=172.34]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: 1280968918417239818
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 902546320 bytes (860 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State          | ID                                | Version           | Source                                          | Signature                                |
	|:-------------- |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAA | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAA | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | forge                             | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | foamfixcore                       | 7.7.4             | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAA | aether_legacy                     | 1.12.2-v1.4.3     | aether_legacy-1.12.2-v1.4.3.jar                 | None                                     |
	| UCHIJAAAAAAAAA | aoa3                              | 3.0.2             | AoA3-3.0.2.jar                                  | None                                     |
	| UCHIJAAAAAAAAA | ctm                               | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
	| UCHIJAAAAAAAAA | appliedenergistics2               | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAAAAAAA | jei                               | 4.14.4.264        | jei_1.12.2-4.14.4.264.jar                       | None                                     |
	| UCHIJAAAAAAAAA | quark                             | r1.5-146          | Quark-r1.5-146.jar                              | None                                     |
	| UCHIJAAAAAAAAA | autoreglib                        | 1.3-26            | AutoRegLib-1.3-26.jar                           | None                                     |
	| UCHIJAAAAAAAAA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAAAAAAA | bettersprinting                   | 2.1.2             | BetterSprinting-1.12.2-v2.1.2.jar               | None                                     |
	| UCHIJAAAAAAAAA | bibliocraft                       | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJAAAAAAAAA | biomesoplenty                     | 7.0.1.2419        | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar   | None                                     |
	| UCHIJAAAAAAAAA | botania                           | r1.10-359         | Botania+r1.10-359.jar                           | None                                     |
	| UCHIJAAAAAAAAA | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAA | chickenchunks                     | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAA | chisel                            | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| UCHIJAAAAAAAAA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | cofhcore                          | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| UCHIJAAAAAAAAA | cofhworld                         | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | endercore                         | 1.12.2-0.5.45     | EnderCore-1.12.2-0.5.45.jar                     | None                                     |
	| UCHIJAAAAAAAAA | thermalfoundation                 | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | thermalexpansion                  | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | enderio                           | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderiointegrationtic             | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderiobase                       | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderioconduits                   | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderioconduitsappliedenergistics | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderioconduitsopencomputers      | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderioconduitsrefinedstorage     | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | mantle                            | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                        | None                                     |
	| UCHIJAAAAAAAAA | natura                            | 1.12.2-4.3.2.66   | natura-1.12.2-4.3.2.66.jar                      | None                                     |
	| UCHIJAAAAAAAAA | forestry                          | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
	| UCHIJAAAAAAAAA | enderiointegrationforestry        | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | twilightforest                    | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar     | None                                     |
	| UCHIJAAAAAAAAA | tconstruct                        | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
	| UCHIJAAAAAAAAA | enderiointegrationticlate         | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderiomachines                   | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | enderiopowertools                 | 5.0.40            | EnderIO-1.12.2-5.0.40.jar                       | None                                     |
	| UCHIJAAAAAAAAA | erebus                            | 1.0.28            | Erebus-1.0.28.jar                               | None                                     |
	| UCHIJAAAAAAAAA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| UCHIJAAAAAAAAA | foamfix                           | 0.10.3-1.12.2     | foamfix-0.10.3-1.12.2.jar                       | None                                     |
	| UCHIJAAAAAAAAA | forgelin                          | 1.8.2             | Forgelin-1.8.2.jar                              | None                                     |
	| UCHIJAAAAAAAAA | ichunutil                         | 7.2.0             | iChunUtil-1.12.2-7.2.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAAAAAAA | gravitygun                        | 7.0.0             | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCHIJAAAAAAAAA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHIJAAAAAAAAA | teslacorelib                      | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAA | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.8-232.jar       | None                                     |
	| UCHIJAAAAAAAAA | industrialmeat                    | 1.12-1.0.2        | industrialmeat-1.12-1.0.2.jar                   | None                                     |
	| UCHIJAAAAAAAAA | journeymap                        | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| UCHIJAAAAAAAAA | jeid                              | 1.0.2-26          | JustEnoughIDs-1.0.2-26.jar                      | None                                     |
	| UCHIJAAAAAAAAA | mystcraft                         | 0.13.6.00         | mystcraft-1.12.2-0.13.6.00.jar                  | None                                     |
	| UCHIJAAAAAAAAA | gbook                             | 2.8.3             | Guidebook-1.12.2-2.8.3.jar                      | None                                     |
	| UCHIJAAAAAAAAA | ltta                              | 1.3.1             | ltta-1.12.2-1.3.1.jar                           | None                                     |
	| UCHIJAAAAAAAAA | mkmmod                            | 1.0               | MobKillMessages-1.12.2-1.0.jar                  | None                                     |
	| UCHIJAAAAAAAAA | moremystcraft                     | 0.5.3             | moremystcraft-1.12.2-0.5.3.jar                  | None                                     |
	| UCHIJAAAAAAAAA | mystcraft_info                    | 1.0.3.0           | mystcraft_info-1.12.2-1.0.3.0.jar               | None                                     |
	| UCHIJAAAAAAAAA | recipehandler                     | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
	| UCHIJAAAAAAAAA | portalgun                         | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAAAAAAA | thermaldynamics                   | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | torohealthmod                     | 1.12.2-11         | torohealth-1.12.2-11.jar                        | None                                     |
	| UCHIJAAAAAAAAA | immersiveengineering              | 0.12-89           | ImmersiveEngineering-0.12-89.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAAAAAAA | thebetweenlands                   | 3.4.6             | TheBetweenlands-3.4.6-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAAAAAAA | teslacorelib_registries           | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
BetterSprintingCore (BetterSprinting-1.12.2-v2.1.2.jar)
  chylex.bettersprinting.system.core.TransformerEntityPlayerSP
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['removed'/932, l='AoA3 Survival World', x=439.31, y=31.00, z=172.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 399.07
	OpenGlRenderer: GeForce 940M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Tslat** [comment]
Fixed
