### ISSUE TITLE
SpongeForge Server issue

### ISSUE THREAD

**Issue by lacoleky** [Tslat/Advent-Of-Ascension#531]
**Mod Version**
What version of the mod are you on?
3.0.2

**Describe the bug**

Not sure if this is a bug or incompatibility with my SpongeForge server.  However, after creating a portal and walking through we are kicked off the server and the client.

Upon dismantling the portal the frame is easily taken apart and yet the portal screen remains.  We have to go into creative mode to destroy the screen.

minecraft 1.12.2
spongeforge 1.12.2-2768-7.1.4
spongeapi 7.1.0-70763aa8

[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Colliding entity with block
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.4]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: net.minecraft.util.ReportedException: Colliding entity with block
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:971) ~[vg.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:545) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) ~[lk$b.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.4]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
Caused by: java.lang.ClassCastException: net.tslat.aoa3.dimension.abyss.AbyssTeleporter cannot be cast to org.spongepowered.api.world.PortalAgent
	at org.spongepowered.common.SpongeImplHooks.registerPortalAgentType(SpongeImplHooks.java:1400) ~[SpongeImplHooks.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:349) ~[EntityUtil.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:220) ~[EntityUtil.class:1.12.2-2768-7.1.4]
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:5063) ~[oq.class:?]
	at net.tslat.aoa3.block.functional.portal.PortalBlock.func_180634_a(PortalBlock.java:176) ~[PortalBlock.class:?]
	at net.minecraft.entity.Entity.redirect$onEntityCollideWithBlockState$zed000(Entity.java:6026) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:964) ~[vg.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:545) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) ~[lk$b.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.4]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more

[Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.1.100:50398
net.minecraft.util.ReportedException: Colliding entity with block
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zio000(NetHandlerPlayServer.java:2050) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: net.tslat.aoa3.dimension.abyss.AbyssTeleporter cannot be cast to org.spongepowered.api.world.PortalAgent
	at org.spongepowered.common.SpongeImplHooks.registerPortalAgentType(SpongeImplHooks.java:1400) ~[SpongeImplHooks.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:349) ~[EntityUtil.class:1.12.2-2768-7.1.4]
	at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:220) ~[EntityUtil.class:1.12.2-2768-7.1.4]
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:5063) ~[oq.class:?]
	at net.tslat.aoa3.block.functional.portal.PortalBlock.func_180634_a(PortalBlock.java:176) ~[PortalBlock.class:?]
	at net.minecraft.entity.Entity.redirect$onEntityCollideWithBlockState$zed000(Entity.java:6026) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:964) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1951) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2386) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 10 more

I have around 50 other mods I use alongside AoA (I'll supply those upon request).

I hope the screenshots are viewable.

![Portal Shot 1](https://user-images.githubusercontent.com/49170449/55360095-6f94c780-54a1-11e9-8230-aca1304a5f97.png)
![Portal Shot 2](https://user-images.githubusercontent.com/49170449/55360101-73284e80-54a1-11e9-999b-3bdada073ef7.png)

**Comment by Immortallis1** [comment]
SpongeForge is known to be unsupported

**Comment by Tslat** [comment]
Stop using spongeforge if you want to be compatible with large mods
