### ISSUE TITLE
internal server error  dont'know why

### ISSUE THREAD

**Issue by acas0701** [Tslat/Advent-Of-Ascension#532]
**Mod Version**
3.0.2

**Describe the bug**
i am make the haven portal and i will go in  but crash

**To Reproduce**
make haven portal
go in
crash

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
---- Minecraft Crash Report ----
// My bad.

Time: 19. 4. 3 오후 2:04
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:280)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:692)
	at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:86)
	at net.minecraft.block.Block.func_180645_a(Block.java:505)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:699)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:427)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:896)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:667)
	at java.lang.Thread.run(Unknown Source)

-- Head --
Thread: Server thread
Stacktrace:
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:280)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:692)
	at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:86)
	at net.minecraft.block.Block.func_180645_a(Block.java:505)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:699)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:427)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['wily_ow'/550, l='world', x=-145.39, y=48.00, z=125.30](wily_ow at -145.39436704747862,48.0,125.30000001192093)]
	Chunk stats: ServerChunkCache: 539 Drop: 0
	Level seed: 917787860693176957
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-100,64,212), Chunk: (at 12,4,4 in -7,13; contains blocks -112,0,208 to -97,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 895217 game time, 36084 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10764 (now: true), thunder time: 7704 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:896)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:667)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 784359560 bytes (748 MB) / 1193279488 bytes (1138 MB) up to 1895825408 bytes (1808 MB)
	JVM Flags: 3 total; -Xms128M -XX:+AggressiveOpts -Xloggc:gc.log
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2812 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source         | Signature |
	|:------ |:------------- |:------------ |:-------------- |:--------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar  | None      |
	| LCHIJA | mcp           | 9.42         | minecraft.jar  | None      |
	| LCHIJA | FML           | 8.0.99.99    | kettle.jar     | None      |
	| LCHIJA | forge         | 14.23.5.2812 | kettle.jar     | None      |
	| LCHIJA | aoa3          | 3.0.2        | AoA3-3.0.2.jar | None      |
	| LCHIJA | adventurebags | 0.9.1        | backpack.jar   | None      |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['wily_ow'/550, l='world', x=-145.39, y=48.00, z=125.30](wily_ow at -145.39436704747862,48.0,125.30000001192093)]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
I don't know what this is, but this is a forge mod - I don't support bukkit
