### ISSUE TITLE
Critical crash with ID 4096

### ISSUE THREAD

**Issue by VMaiko1634** [Tslat/Advent-Of-Ascension#609]
**Mod Version**
3.0.2

**Forge**
1.12.2-forge1.12.2-14.23.5.2836

**Log**
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.grim3212.mc.pack.decor.block.DecorBlocks.initBlocks(DecorBlocks.java:114)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1200_DecorBlocks_initBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'download any kind of modpack, e.g FTB'
2. Add this mod
3. Start Launcher
4. at the end of phase 1 (2/7) produce crash.

**Comment by Tslat** [comment]
This has nothing to do with me - your config for decor blocks looks to be set up incorrectly
