### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SettingDust** [Tslat/Advent-Of-Ascension#643]
**Mod Version**
3.1.1

**Describe the bug**
```
[22:03:20] [Thread-40/INFO] [aoa3]: Exception encountered while running an AoALeaderboard task, skipping. 
[22:03:20] [Thread-40/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.AoALeaderboard:run:48]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 
[22:03:20] [Thread-40/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.AoALeaderboard:run:48]: 	at java.util.ArrayList.rangeCheck(Unknown Source) 
[22:03:20] [Thread-40/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.AoALeaderboard:run:48]: 	at java.util.ArrayList.get(Unknown Source) 
[22:03:20] [Thread-40/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.AoALeaderboard:run:48]: 	at net.tslat.aoa3.library.leaderboard.Leaderboard.addOrUpdatePlayer(Leaderboard.java:36) 
[22:03:20] [Thread-40/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.AoALeaderboard:run:48]: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard$UpdatePlayerStat.run(AoALeaderboard.java:148) 
[22:03:20] [Thread-40/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.AoALeaderboard:run:48]: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard.run(AoALeaderboard.java:43) 
```

**To Reproduce**
Steps to reproduce the behaviour:
Run server(sponge 7.1.5)

**Comment by Immortallis1** [comment]
SpongeForge is not supported.

**Comment by Tslat** [comment]
In this case it's probably the leaderboard

There'sa reason it's not released yet;)
