### ISSUE TITLE
I don't know what the problem is, but I want to submit it to you :)

### ISSUE THREAD

**Issue by 3269199948** [Tslat/Advent-Of-Ascension#727]
[17:27:09] [Thread-17/INFO] [aoa3]: Exception encountered while running an AoALeaderboard task, skipping.
[17:27:09] [Thread-17/WARN] []: java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
[17:27:09] [Thread-17/WARN] []: 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[17:27:09] [Thread-17/WARN] []: 	at java.util.ArrayList.get(ArrayList.java:433)
[17:27:09] [Thread-17/WARN] []: 	at net.tslat.aoa3.library.leaderboard.Leaderboard.addOrUpdatePlayer(Leaderboard.java:36)
[17:27:09] [Thread-17/WARN] []: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard$UpdatePlayerStat.run(AoALeaderboard.java:160)
[17:27:09] [Thread-17/WARN] []: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard.run(AoALeaderboard.java:43)

**Comment by Tslat** [comment]
Thanks for the report - what version of the mod are you on?

**Comment by 3269199948** [comment]
> 感谢您的报告 - 您使用的是什么版本的mod？

3.1.2.b,He appeared a long time ago, but I am not sure if it is a bug, so I will submit it now.

**Comment by Tslat** [comment]
Was it on 3.1.2.b that you got that error? or on a previous version?

**Comment by 3269199948** [comment]
> Was it on 3.1.2.b that you got that error? or on a previous version?
I am using 3.1.2.b, this version reported this error.
