### ISSUE TITLE
Unable to access leaderboard

### ISSUE THREAD

**Issue by LemADEC** [Tslat/Advent-Of-Ascension#747]
**Mod Version**
3.1.2.b

**Describe the bug**
At boot, the console is spammed with error about accessing the leaderboard.

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot the server

**Expected behavior**
No error, no console spam.
Consider outputting the file name in the error message so we can investigate further.

**Screenshots**
```
[15:41:30] [Thread-14/ERROR] [aoa3]: Unable to load leaderboard from file: I can't access the file!
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]: java.io.EOFException
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:861)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler.loadLeaderboard(LeaderboardDataHandler.java:63)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler.init(LeaderboardDataHandler.java:32)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at net.tslat.aoa3.library.leaderboard.AoALeaderboard$InitTask.run(AoALeaderboard.java:96)
[15:41:30] [Thread-14/INFO] [STDERR]: [net.tslat.aoa3.library.leaderboard.LeaderboardDataHandler:loadLeaderboard:82]:   at net.tslat.aoa3.library.leaderboard.AoALeaderboard.run(AoALeaderboard.java:43)
```

**Comment by Tslat** [comment]
Thanks for reporting.

To solve it for yourself you can either disable the leaderboard in the config, or delete the leaderboard files in your world folder.
