### ISSUE TITLE
The game will crash when hunting mobs in the vox'ponds dimension.

### ISSUE THREAD

**Issue by jianan46** [Tslat/Advent-Of-Ascension#757]
Here is the detail.Once I start the game ,the game crash.What should I do?

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/8/19 4:00 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.tslat.aoa3.entity.projectiles.staff.BaseEnergyShot.func_70184_a(BaseEnergyShot.java:144)
	at net.tslat.aoa3.entity.projectiles.staff.BaseEnergyShot.func_70071_h_(BaseEnergyShot.java:222)
	at net.tslat.aoa3.entity.projectiles.blaster.EntityHellBubbleShot.func_70071_h_(EntityHellBubbleShot.java:25)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.tslat.aoa3.entity.projectiles.staff.BaseEnergyShot.func_70184_a(BaseEnergyShot.java:144)
	at net.tslat.aoa3.entity.projectiles.staff.BaseEnergyShot.func_70071_h_(BaseEnergyShot.java:222)
	at net.tslat.aoa3.entity.projectiles.blaster.EntityHellBubbleShot.func_70071_h_(EntityHellBubbleShot.java:25)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: aoa3:hell_bubble (net.tslat.aoa3.entity.projectiles.blaster.EntityHellBubbleShot)
	Entity ID: 409
	Entity Name: 能量镭射
	Entity's Exact location: -219.21, 39.94, 249.42
	Entity's Block location: World: (-220,39,249), Chunk: (at 4,2,9 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.88, -0.09, 0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 干他丫的
	All players: 1 total; [EntityPlayerMP['jianan'/378, l='干他丫的', x=-193.90, y=39.00, z=252.28]]
	Chunk stats: ServerChunkCache: 49 Drop: 0
	Level seed: -1730350215359258609
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 325291616 bytes (310 MB) / 2125463552 bytes (2027 MB) up to 3262644224 bytes (3111 MB)
	JVM Flags: 2 total; -Xmx3500m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | aoa3      | 3.1.2.b      | AoA3-3.1.2.b.jar              | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['jianan'/378, l='干他丫的', x=-193.90, y=39.00, z=252.28]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jianan46** [comment]
emmm,I have solved the problem,by deleting the saves of the vox'pond.But it should be a bug .

**Comment by Tslat** [comment]
Fixed in 3.2
