### ISSUE TITLE
The Mod has serious error in my server and cilent

### ISSUE THREAD

**Issue by 1640946640** [Tslat/Advent-Of-Ascension#796]
As you can see,this Mod page will be scrambled(https://s2.ax1x.com/2019/08/06/ehUL1H.md.png)
And my server always report error,can you fix it?
```
[15:15:17] [Thread-73/INFO] [aoa3]: Exception encountered while running an AoALeaderboard task, skipping.
[15:15:17] [Thread-73/WARN] []: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
[15:15:17] [Thread-73/WARN] []: 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[15:15:17] [Thread-73/WARN] []: 	at java.util.ArrayList.get(ArrayList.java:433)
[15:15:17] [Thread-73/WARN] []: 	at net.tslat.aoa3.library.leaderboard.Leaderboard.addOrUpdatePlayer(Leaderboard.java:36)
[15:15:17] [Thread-73/WARN] []: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard$UpdatePlayerStat.run(AoALeaderboard.java:148)
[15:15:17] [Thread-73/WARN] []: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard.run(AoALeaderboard.java:43)
[15:16:43] [Thread-73/INFO] [aoa3]: Exception encountered while running an AoALeaderboard task, skipping.
[15:16:43] [Thread-73/WARN] []: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
[15:16:43] [Thread-73/WARN] []: 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[15:16:43] [Thread-73/WARN] []: 	at java.util.ArrayList.get(ArrayList.java:433)
[15:16:43] [Thread-73/WARN] []: 	at net.tslat.aoa3.library.leaderboard.Leaderboard.addOrUpdatePlayer(Leaderboard.java:36)
[15:16:43] [Thread-73/WARN] []: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard$UpdatePlayerStat.run(AoALeaderboard.java:148)
[15:16:43] [Thread-73/WARN] []: 	at net.tslat.aoa3.library.leaderboard.AoALeaderboard.run(AoALeaderboard.java:43)
```

**Comment by Tslat** [comment]
Thanks for reporting it

Disable the AoA Leaderboard in your config files (on the server and client)
It'll fix that up for you
