### ISSUE TITLE
Can't summon boss or use certain items 

### ISSUE THREAD

**Issue by Spekkun** [Tslat/Advent-Of-Ascension#934]
**Mod Version**
AoA3-3.0

**Describe the bug**
If I try to summon a boss, I.E. Smash the Troll King, it won't work. Similarly, totems can't be placed. 

**To Reproduce**
1. Try to place Troll Idol (or spawn egg) on the ground. Nothing happens. Similarly for Soul Bone Totem.

**Expected behavior**
Expect the Troll King to be summoned, but nothing happens. Totems never place either.

**Screenshots**
I do get this error

[20:55:27] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/tslat/aoa3/client/fx/audio/BossMusicSound
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoClassDefFoundError: net/tslat/aoa3/client/fx/audio/BossMusicSound
	at net.tslat.aoa3.entity.boss.smash.EntitySmash.<init>(EntitySmash.java:42) ~[EntitySmash.class:?]
	at net.tslat.aoa3.item.misc.summon.TrollIdol.func_180614_a(TrollIdol.java:29) ~[TrollIdol.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:492) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by EatingSilencer** [comment]
You are using an out of date version of the mod. 

Update your mod and that will fix this.
